Update deltaservice

diff --git a/src/deb/init.d/deltaservice b/src/deb/init.d/deltaservice
--- a/src/deb/init.d/deltaservice
+++ b/src/deb/init.d/deltaservice
@@ -1,30 +1,69 @@
-#!/bin/sh
 
-REQUIRED_VERSION=1.8
-jumpto() {
-   echo "Installing oracle java8"
-   sudo apt-get install -y python-software-properties debconf-utils
-   sudo add-apt-repository -y ppa:webupd8team/java
-   sudo apt-get update
-   echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
-   sudo apt-get install -y oracle-java8-installer
-   sudo apt-get install oracle-java8-set-default
+
+#!/bin/sh
+### BEGIN INIT INFO
+# Provides:          <NAME>
+# Required-Start:    $local_fs $network $named $time $syslog
+# Required-Stop:     $local_fs $network $named $time $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Description:       <DESCRIPTION>
+### END INIT INFO
+
+SCRIPT=java -jar /apps/delta/provisioning-1.0-SNAPSHOT.jar
+RUNAS=root
+
+PIDFILE=/var/run/<NAME>.pid
+LOGFILE=/var/log/<NAME>.log
+
+start() {
+  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
+    echo 'Service already running' >&2
+    return 1
+  fi
+  echo 'Starting service…' >&2
+  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
+  su -c "$CMD" $RUNAS > "$PIDFILE"
+  echo 'Service started' >&2
 }
 
-java -version 2> tmp.ver
-VERSION=`cat tmp.ver | grep "java version" | awk '{ print substr($3, 2, length($3)-2); }'`
-rm tmp.ver
-echo "java current version: $VERSION and expected version: $REQUIRED_VERSION"
-VERSION=`echo $VERSION | awk '{ print substr($1, 1, 3); }' | sed -e 's;\.;0;g'`
-REQUIRED_VERSION=`echo $REQUIRED_VERSION | awk '{ print substr($1, 1, 3); }' | sed -e 's;\.;0;g'`
-if [ $VERSION ]
-then
-        if [ $REQUIRED_VERSION -gt $VERSION ]
-        then
-                jumpto
-        fi
-        sudo java -jar /apps/delta/provisioning-1.0-SNAPSHOT.jar > $1 2> /apps/delta/provisioning-1.0.log &
-else
-   jumpto
-   sudo java -jar /apps/delta/provisioning-1.0-SNAPSHOT.jar > $1 2> /apps/delta/provisioning-1.0.log &
-fi
+stop() {
+  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
+    echo 'Service not running' >&2
+    return 1
+  fi
+  echo 'Stopping service…' >&2
+  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+  echo 'Service stopped' >&2
+}
+
+uninstall() {
+  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+  local SURE
+  read SURE
+  if [ "$SURE" = "yes" ]; then
+    stop
+    rm -f "$PIDFILE"
+    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
+    update-rc.d -f <NAME> remove
+    rm -fv "$0"
+  fi
+}
+
+case "$1" in
+  start)
+    start
+    ;;
+  stop)
+    stop
+    ;;
+  uninstall)
+    uninstall
+    ;;
+  retart)
+    stop
+    start
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|restart|uninstall}"
+esac
